language: cpp
sudo: required

os:
  - linux
  - osx

dist: trusty

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

install:
  - source build/InstallMono.sh
  - build/InstallNugets.sh  
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then PREMAKE=build/premake5-linux-64; else PREMAKE=build/premake5-osx; fi
  - $PREMAKE --file=build/scripts/LLVM.lua download_llvm

script: |
  build/Compile.sh && build/RunTests.sh
